/**
 * BSReportExcelService.js
 * Generates a 5-sheet Excel workbook: BS | BS Schedule | PL | PL Schedule | FA Note 9
 *
 * API INTEGRATION: This file stays unchanged. Update BSReportDummyData.js when backend is ready.
 */

import ExcelJS from 'exceljs'
import { saveAs } from 'file-saver'
import {
  COMPANY_META,
  BS_DATA,
  PL_DATA,
  BS_SCHEDULE_DATA,
  PL_SCHEDULE_DATA,
  FA_NOTE_DATA,
} from '../data/BSReportDummyData'

// ─── CONSTANTS ─────────────────────────────────────────────────────────────────

const NUM_FMT = '##,##,##,##0;(##,##,##,##0);"-"'

const C = {
  navyBlue: 'FF1F3864',
  medBlue: 'FF4472C4',
  lightBlue: 'FFDAE3F3',
  paleBlue: 'FFEFF3FB',
  gold: 'FFFFD966',
  lightGold: 'FFFFF2CC',
  lightGray: 'FFF2F2F2',
  white: 'FFFFFFFF',
  black: 'FF000000',
  gray: 'FF808080',
  darkBlue: 'FF2E4D8C',
}

// ─── STYLE HELPERS ─────────────────────────────────────────────────────────────

const applyStyle = (cell, opts = {}) => {
  const {
    bold = false, italic = false, size = 10, color = C.black,
    bg = null, hAlign = 'left', vAlign = 'middle', wrapText = false,
    numFmt = null, border = 'thin', borderColor = 'FFBFBFBF', underline = false,
  } = opts

  cell.font = { bold, italic, size, color: { argb: color }, name: 'Calibri', underline }
  cell.alignment = { horizontal: hAlign, vertical: vAlign, wrapText }
  if (bg) cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: bg } }
  if (numFmt) cell.numFmt = numFmt
  if (border) {
    const b = { style: border, color: { argb: borderColor } }
    cell.border = { top: b, left: b, bottom: b, right: b }
  }
}

/** Safe merge — wraps in try/catch so already-merged cells won't crash */
const safeMerge = (ws, r, c1, c2) => {
  try {
    if (c1 < c2) ws.mergeCells(r, c1, r, c2)
  } catch (_) { /* already merged — ignore */ }
}

const mergeCenter = (ws, r, c1, c2, value, opts = {}) => {
  safeMerge(ws, r, c1, c2)
  const cell = ws.getCell(r, c1)
  cell.value = value
  applyStyle(cell, opts)
  return cell
}

const fmt = (n) => {
  if (n === 0 || n === null || n === undefined) return null
  return Number(n)
}

// ─── SHARED: COMPANY HEADER ────────────────────────────────────────────────────

const addCompanyHeader = (ws, totalCols, reportTitle) => {
  let r = 1
  mergeCenter(ws, r, 1, totalCols, COMPANY_META.name, {
    bold: true, size: 14, color: C.navyBlue, hAlign: 'center', underline: true,
  })
  ws.getRow(r).height = 24; r++
  mergeCenter(ws, r, 1, totalCols, COMPANY_META.formerly1, {
    italic: true, size: 10, color: C.darkBlue, hAlign: 'center',
  })
  ws.getRow(r).height = 16; r++
  mergeCenter(ws, r, 1, totalCols, COMPANY_META.formerly2, {
    italic: true, size: 10, color: C.darkBlue, hAlign: 'center',
  })
  ws.getRow(r).height = 16; r++
  mergeCenter(ws, r, 1, totalCols, reportTitle, {
    bold: true, size: 12, color: C.black, hAlign: 'center',
  })
  ws.getRow(r).height = 20; r++
  ws.getRow(r).height = 6; r++ // spacer
  return r
}

const addFooter = (ws, r, totalCols) => {
  ws.getRow(r).height = 8; r++
  mergeCenter(ws, r, 1, totalCols, 'For I SMART FACITECH PVT LTD', {
    bold: true, size: 10, hAlign: 'right',
  })
  ws.getRow(r).height = 16; r++
  ws.getCell(r, 1).value = 'Vinayak Bhise  |  DIN: 02711584'
  ws.getCell(r, 1).font = { bold: true, size: 10 }
  const mid = Math.ceil(totalCols / 2)
  ws.getCell(r, mid).value = 'Shobhana Bagwe  |  DIN: 02711562'
  ws.getCell(r, mid).font = { bold: true, size: 10 }
  ws.getRow(r).height = 18; r++
  mergeCenter(ws, r, 1, totalCols,
    `Generated by iSmart Accounts System on ${new Date().toLocaleString('en-IN')}`,
    { size: 8, italic: true, color: C.gray, hAlign: 'center' })
  ws.getRow(r).height = 14
}

// ═══════════════════════════════════════════════════════════════════════════════
// SHEET 1: BALANCE SHEET
// ═══════════════════════════════════════════════════════════════════════════════

const buildBSSheet = (wb) => {
  const ws = wb.addWorksheet('BS', {
    views: [{ state: 'frozen', xSplit: 0, ySplit: 7 }],
    pageSetup: { paperSize: 9, orientation: 'landscape', fitToPage: true, fitToWidth: 1 },
  })
  //  A=col1(sr), B=col2(sr sub), C=col3(particulars), D=col4(note), E=col5(CY), F=col6(PY)
  ws.columns = [
    { width: 4 }, { width: 4 }, { width: 42 },
    { width: 8 }, { width: 20 }, { width: 20 },
  ]
  const TC = 6
  let r = addCompanyHeader(ws, TC, 'Balance Sheet as on 31st March 2024')

  // ── Column Headers ──────────────────────────────────────────────────────────
  safeMerge(ws, r, 1, 3)
  ws.getCell(r, 1).value = 'Particulars'
  applyStyle(ws.getCell(r, 1), { bold: true, size: 11, bg: C.navyBlue, color: C.white, hAlign: 'center', border: 'medium', borderColor: C.black })
  ws.getCell(r, 4).value = 'Note\nNo'
  applyStyle(ws.getCell(r, 4), { bold: true, size: 11, bg: C.navyBlue, color: C.white, hAlign: 'center', wrapText: true, border: 'medium', borderColor: C.black })
  ws.getCell(r, 5).value = '31st March 2024'
  applyStyle(ws.getCell(r, 5), { bold: true, size: 11, bg: C.navyBlue, color: C.white, hAlign: 'center', border: 'medium', borderColor: C.black })
  ws.getCell(r, 6).value = '31st March 2023'
  applyStyle(ws.getCell(r, 6), { bold: true, size: 11, bg: C.navyBlue, color: C.white, hAlign: 'center', border: 'medium', borderColor: C.black })
  ws.getRow(r).height = 26; r++

  // ── Helper: section banner (full width) ─────────────────────────────────────
  const sectionBanner = (label) => {
    mergeCenter(ws, r, 1, TC, label, {
      bold: true, size: 11, bg: C.lightBlue, color: C.navyBlue, border: 'thin',
    })
    ws.getRow(r).height = 18; r++
  }

  // ── Helper: sub-group heading (cols 2-6 merged, col 1 = number) ─────────────
  const groupHeading = (srNo, label) => {
    ws.getCell(r, 1).value = srNo
    applyStyle(ws.getCell(r, 1), { bold: true, size: 10, bg: C.lightGold, border: 'thin' })
    safeMerge(ws, r, 2, TC)
    ws.getCell(r, 2).value = label
    applyStyle(ws.getCell(r, 2), { bold: true, underline: true, size: 10, bg: C.lightGold, border: 'thin' })
    ws.getRow(r).height = 17; r++
  }

  // ── Helper: data row (cols 1-3 merged for label, col4=note, col5=CY, col6=PY) ─
  const dataRow = (label, note, cy, py, opts = {}) => {
    const { bold = false, isTotal = false, indent = '' } = opts
    const bg = isTotal ? C.lightGold : null
    safeMerge(ws, r, 1, 3)
    ws.getCell(r, 1).value = indent + label
    applyStyle(ws.getCell(r, 1), { bold: bold || isTotal, size: 10, bg, border: 'thin', wrapText: true })
    ws.getCell(r, 4).value = note || ''
    applyStyle(ws.getCell(r, 4), { hAlign: 'center', size: 10, bg, border: 'thin' })
    ;[cy, py].forEach((v, i) => {
      const cell = ws.getCell(r, i + 5)
      const n = fmt(v)
      if (n !== null) { cell.value = n; cell.numFmt = NUM_FMT }
      else { cell.value = '-' }
      applyStyle(cell, { bold: bold || isTotal, hAlign: 'right', size: 10, bg, border: 'thin' })
    })
    ws.getRow(r).height = 17; r++
  }

  // ── Helper: total / grand-total banner row (full dark header style) ──────────
  const totalBanner = (label, cy, py) => {
    safeMerge(ws, r, 1, 4)
    ws.getCell(r, 1).value = label
    applyStyle(ws.getCell(r, 1), { bold: true, size: 11, bg: C.navyBlue, color: C.white, border: 'medium', borderColor: C.black })
    ;[cy, py].forEach((v, i) => {
      const cell = ws.getCell(r, i + 5)
      const n = fmt(v)
      if (n !== null) { cell.value = n; cell.numFmt = NUM_FMT }
      else { cell.value = '-' }
      applyStyle(cell, { bold: true, size: 11, hAlign: 'right', bg: C.navyBlue, color: C.white, border: 'medium', borderColor: C.black })
    })
    ws.getRow(r).height = 20; r++
  }

  const spacer = () => { ws.getRow(r).height = 6; r++ }

  // ════════════════════════════════════════════════
  // I. EQUITY AND LIABILITIES
  // ════════════════════════════════════════════════
  sectionBanner('I.  EQUITY AND LIABILITIES')
  const eq = BS_DATA.equityAndLiabilities

  // 1. Shareholders' Funds
  groupHeading('1', "Shareholder's Funds")
  dataRow('(a) Share Capital', eq.shareholdersFunds.shareCapital.note, eq.shareholdersFunds.shareCapital.cy, eq.shareholdersFunds.shareCapital.py, { indent: '    ' })
  dataRow('(b) Reserves and Surplus', eq.shareholdersFunds.reservesAndSurplus.note, eq.shareholdersFunds.reservesAndSurplus.cy, eq.shareholdersFunds.reservesAndSurplus.py, { indent: '    ' })
  dataRow('', null, eq.shareholdersFunds.totalShareholdersFunds.cy, eq.shareholdersFunds.totalShareholdersFunds.py, { isTotal: true })

  // 2. Non-Current Liabilities
  groupHeading('2', 'Non-Current Liabilities')
  const ncl = eq.nonCurrentLiabilities
  dataRow('(a) Long-term borrowings', ncl.longTermBorrowings.note, ncl.longTermBorrowings.cy, ncl.longTermBorrowings.py, { indent: '    ' })
  dataRow('(b) Deferred tax liabilities', null, ncl.deferredTaxLiabilities.cy, ncl.deferredTaxLiabilities.py, { indent: '    ' })
  dataRow('(c) Other Long term liabilities', null, ncl.otherLongTermLiabilities.cy, ncl.otherLongTermLiabilities.py, { indent: '    ' })
  dataRow('(d) Long term provisions', null, ncl.longTermProvisions.cy, ncl.longTermProvisions.py, { indent: '    ' })
  dataRow('', null, ncl.totalNonCurrentLiabilities.cy, ncl.totalNonCurrentLiabilities.py, { isTotal: true })

  // 3. Current Liabilities
  groupHeading('3', 'Current Liabilities')
  const cl = eq.currentLiabilities
  dataRow('(a) Short-term borrowings', cl.shortTermBorrowings.note, cl.shortTermBorrowings.cy, cl.shortTermBorrowings.py, { indent: '    ' })
  dataRow('(b) Trade payables', cl.tradePayablesMSME.note || '', null, null, { indent: '    ' })
  dataRow('     Total outstanding dues of micro enterprises and small enterprises', null, cl.tradePayablesMSME.cy, cl.tradePayablesMSME.py, { indent: '    ' })
  dataRow('     Total outstanding dues of creditors other than micro enterprises and small enterprises', null, cl.tradePayablesOthers.cy, cl.tradePayablesOthers.py, { indent: '    ' })
  ws.getRow(r - 1).height = 30
  dataRow('(c) Other current liabilities', cl.otherCurrentLiabilities.note, cl.otherCurrentLiabilities.cy, cl.otherCurrentLiabilities.py, { indent: '    ' })
  dataRow('(d) Short-term provisions', cl.shortTermProvisions.note, cl.shortTermProvisions.cy, cl.shortTermProvisions.py, { indent: '    ' })
  dataRow('', null, cl.totalCurrentLiabilities.cy, cl.totalCurrentLiabilities.py, { isTotal: true })

  totalBanner('TOTAL', eq.grandTotal.cy, eq.grandTotal.py)
  spacer()

  // ════════════════════════════════════════════════
  // II. ASSETS
  // ════════════════════════════════════════════════
  sectionBanner('II.  ASSETS')
  const assets = BS_DATA.assets

  // 1. Non-current assets
  groupHeading('1', 'Non-current assets')
  const nca = assets.nonCurrentAssets
  dataRow('(a) Property, Plant and Equipment', nca.ppe.note, nca.ppe.cy, nca.ppe.py, { indent: '    ' })
  dataRow('(b) Intangible assets', nca.intangibleAssets.note, nca.intangibleAssets.cy, nca.intangibleAssets.py, { indent: '    ' })
  dataRow('(c) Non-current investments', null, nca.nonCurrentInvestments.cy, nca.nonCurrentInvestments.py, { indent: '    ' })
  dataRow('(d) Deferred tax assets (Net)', nca.deferredTaxAssetsNet.note, nca.deferredTaxAssetsNet.cy, nca.deferredTaxAssetsNet.py, { indent: '    ' })
  dataRow('(e) Long term loans and advances', null, nca.longTermLoansAndAdvances.cy, nca.longTermLoansAndAdvances.py, { indent: '    ' })

  // 2. Current assets
  groupHeading('2', 'Current assets')
  const ca = assets.currentAssets
  dataRow('(a) Inventories', null, ca.inventories.cy, ca.inventories.py, { indent: '    ' })
  dataRow('(b) Trade receivables', ca.tradeReceivables.note, ca.tradeReceivables.cy, ca.tradeReceivables.py, { indent: '    ' })
  dataRow('(c) Cash and cash equivalents', ca.cashAndCashEquivalents.note, ca.cashAndCashEquivalents.cy, ca.cashAndCashEquivalents.py, { indent: '    ' })
  dataRow('(d) Short-term loans and advances', ca.shortTermLoansAndAdvances.note, ca.shortTermLoansAndAdvances.cy, ca.shortTermLoansAndAdvances.py, { indent: '    ' })
  dataRow('(e) Other current assets', ca.otherCurrentAssets.note, ca.otherCurrentAssets.cy, ca.otherCurrentAssets.py, { indent: '    ' })

  totalBanner('Total...', assets.grandTotal.cy, assets.grandTotal.py)
  spacer()

  // Notes to Accounts
  safeMerge(ws, r, 1, 3)
  ws.getCell(r, 1).value = 'Notes to Accounts'
  applyStyle(ws.getCell(r, 1), { bold: true, size: 10, border: 'thin' })
  ws.getCell(r, 4).value = '1'
  applyStyle(ws.getCell(r, 4), { hAlign: 'center', size: 10, border: 'thin' })
  ws.getCell(r, 5).value = '-'; ws.getCell(r, 6).value = '-'
  applyStyle(ws.getCell(r, 5), { border: 'thin' }); applyStyle(ws.getCell(r, 6), { border: 'thin' })
  ws.getRow(r).height = 17; r++

  spacer(); r++
  addFooter(ws, r, TC)
}

// ═══════════════════════════════════════════════════════════════════════════════
// SHEET 2: BS SCHEDULE
// ═══════════════════════════════════════════════════════════════════════════════

const buildBSScheduleSheet = (wb) => {
  const ws = wb.addWorksheet('BS Schedule')
  ws.columns = [
    { width: 48, wrapText: true }, { width: 18 }, { width: 18 }, { width: 18 }, { width: 18 },
  ]
  const TC = 5
  let r = addCompanyHeader(ws, TC, 'Schedules forming part of Balance Sheet as on 31st March 2024')

  const noteHdr = (title) => {
    mergeCenter(ws, r, 1, TC, title, {
      bold: true, size: 11, bg: C.navyBlue, color: C.white, border: 'medium', borderColor: C.black,
    })
    ws.getRow(r).height = 20; r++
  }

  const colHdrs = (labels) => {
    labels.forEach((lbl, i) => {
      ws.getCell(r, i + 1).value = lbl
      applyStyle(ws.getCell(r, i + 1), {
        bold: true, size: 10, bg: C.lightBlue, color: C.navyBlue,
        hAlign: 'center', border: 'thin', wrapText: true, vAlign: 'middle',
      })
    })
    ws.getRow(r).height = 32; r++
  }

  const subHead = (label) => {
    mergeCenter(ws, r, 1, TC, label, {
      bold: true, size: 10, bg: C.paleBlue, color: C.navyBlue, border: 'thin',
    })
    ws.getRow(r).height = 16; r++
  }

  const row5 = (label, v2, v3, v4, v5, opts = {}) => {
    const { bold = false, isTotal = false, indent = 0 } = opts
    const bg = isTotal ? C.lightGold : null
    ws.getCell(r, 1).value = '  '.repeat(indent) + label
    applyStyle(ws.getCell(r, 1), { bold: bold || isTotal, size: 10, bg, border: 'thin', wrapText: true })
    ;[v2, v3, v4, v5].forEach((v, i) => {
      const cell = ws.getCell(r, i + 2)
      if (v !== null && v !== undefined && typeof v === 'number' && v !== 0) {
        cell.value = fmt(v); cell.numFmt = NUM_FMT
      } else { cell.value = (v === null || v === undefined) ? '-' : (v === 0 ? '-' : v) }
      applyStyle(cell, { bold: bold || isTotal, hAlign: 'right', size: 10, bg, border: 'thin' })
    })
    ws.getRow(r).height = 17; r++
  }

  const blank = () => { ws.getRow(r).height = 8; r++ }

  const S = BS_SCHEDULE_DATA

  // ── Note 2: Share Capital ─────────────────────────────────────────────────
  noteHdr(S.note2_shareCapital.title)
  colHdrs(['Particulars', '31st March 2024\n(No.)', '31st March 2024\n(Amount ₹)', '31st March 2023\n(No.)', '31st March 2023\n(Amount ₹)'])

  subHead('Authorised Share Capital')
  const auth = S.note2_shareCapital.authorisedCapital
  row5(auth.description, auth.cyNumber, auth.cyAmount, auth.pyNumber, auth.pyAmount, { indent: 1 })

  subHead('Issued, Subscribed & Fully Paid Up')
  const isp = S.note2_shareCapital.issuedSubscribedPaidUp
  row5(isp.description, isp.cyNumber, isp.cyAmount, isp.pyNumber, isp.pyAmount, { indent: 1 })
  const t2 = S.note2_shareCapital.total
  row5('TOTAL...', t2.cyNumber, t2.cyAmount, t2.pyNumber, t2.pyAmount, { isTotal: true })
  blank()

  subHead('Reconciliation of shares outstanding')
  colHdrs(['Particulars', '31st March 2024\n(No.)', '31st March 2024\n(Amount ₹)', '31st March 2023\n(No.)', '31st March 2023\n(Amount ₹)'])
  S.note2_shareCapital.reconciliation.forEach(item => {
    const isLast = item.particulars.includes('end of the year')
    row5(item.particulars, item.cyNumber, item.cyAmount, item.pyNumber, item.pyAmount, { isTotal: isLast, bold: isLast })
  })
  blank()

  subHead('Terms/rights attached to equity shares')
  mergeCenter(ws, r, 1, TC, S.note2_shareCapital.termsRights, {
    size: 9, italic: true, wrapText: true, border: 'thin',
  })
  ws.getRow(r).height = 52; r++
  blank()

  subHead('Equity Shares held (More than 5%)')
  colHdrs(['Name of Shareholder', '31st Mar 2024\nNo. of Shares', '31st Mar 2024\n% Holding', '31st Mar 2023\nNo. of Shares', '31st Mar 2023\n% Holding'])
  S.note2_shareCapital.shareholdersAbove5Percent.forEach(sh => {
    row5(sh.name, sh.cyShares, sh.cyPercent, sh.pyShares, sh.pyPercent)
  })
  row5('Total', S.note2_shareCapital.totalShares.cy, null, S.note2_shareCapital.totalShares.py, null, { isTotal: true })
  blank()

  // ── Note 3: Reserve & Surplus ─────────────────────────────────────────────
  noteHdr(S.note3_reserveAndSurplus.title)
  colHdrs(['Particular', '31st March 2024', '31st March 2023', '', ''])
  subHead('Profit & Loss Account')
  const pl3 = S.note3_reserveAndSurplus.profitAndLoss
  row5('Opening Balance', pl3.openingBalance.cy, pl3.openingBalance.py, null, null, { indent: 1 })
  row5('Add: Profit (Loss) for the period', pl3.addProfitLoss.cy, pl3.addProfitLoss.py, null, null, { indent: 1 })
  row5('TOTAL...', pl3.total.cy, pl3.total.py, null, null, { isTotal: true })
  blank()

  // ── Simple 2-col note helper ─────────────────────────────────────────────
  const simpleNote = (noteData, extraLabel = null) => {
    noteHdr(noteData.title)
    colHdrs(['Particular', '31st March 2024', '31st March 2023', '', ''])
    if (extraLabel) subHead(extraLabel)
    noteData.items.forEach(item => row5(item.name, item.cy, item.py, null, null, { indent: 1 }))
    row5('TOTAL...', noteData.total.cy, noteData.total.py, null, null, { isTotal: true })
    blank()
  }

  simpleNote(S.note4_longTermBorrowings, 'Unsecured Loans')
  simpleNote(S.note5_shortTermBorrowings, S.note5_shortTermBorrowings.label)

  // ── Note 6: Trade Payables ────────────────────────────────────────────────
  noteHdr(S.note6_tradePayables.title)
  mergeCenter(ws, r, 1, TC, S.note6_tradePayables.msmeNote, {
    size: 9, italic: true, wrapText: true, border: 'thin',
  })
  ws.getRow(r).height = 32; r++

  ;[S.note6_tradePayables.currentYear, S.note6_tradePayables.previousYear].forEach(yr => {
    subHead(yr.label)
    colHdrs(['Particulars', 'Less than\n6 Months', '6 Mo to\n1 Year', '1 to 2\nYears', 'Total'])
    yr.rows.forEach(row => {
      row5(row.category, row.lt6, row.m6to1y, row.m1to2y, row.total)
    })
    blank()
  })

  simpleNote(S.note7_otherCurrentLiabilities)
  simpleNote(S.note8_shortTermProvisions)
  simpleNote(S.note10_deferredTaxAssets)

  // ── Note 11: Trade Receivables ────────────────────────────────────────────
  noteHdr(S.note11_tradeReceivables.title)
  colHdrs(['Trade Receivables', '31st March 2024 ₹', '31st March 2023 ₹', '', ''])
  const n11 = S.note11_tradeReceivables
  subHead('Debts outstanding exceeding six months')
  row5('Unsecured, considered good', n11.debtsExceedingSixMonths.unsecuredGood.cy, n11.debtsExceedingSixMonths.unsecuredGood.py, null, null, { indent: 1 })
  row5('Less: Provision for doubtful debts', null, null, null, null, { indent: 1 })
  row5('Subtotal', n11.debtsExceedingSixMonths.subtotal.cy, n11.debtsExceedingSixMonths.subtotal.py, null, null, { bold: true })
  subHead('Other Debts')
  row5('Unsecured, considered good', n11.otherDebts.unsecuredGood.cy, n11.otherDebts.unsecuredGood.py, null, null, { indent: 1 })
  row5('Less: Provision', null, null, null, null, { indent: 1 })
  row5('Net Other Debts', n11.otherDebts.net.cy, n11.otherDebts.net.py, null, null, { bold: true })
  row5('Total', n11.total.cy, n11.total.py, null, null, { isTotal: true })
  blank()

  ;[
    { label: 'Trade Receivables Ageing – Current Year (31st March 2024)', rows: n11.currentYearAgeing, tot: n11.cyAgeingTotal },
    { label: 'Trade Receivables Ageing – Previous Year (31st March 2023)', rows: n11.previousYearAgeing, tot: n11.pyAgeingTotal },
  ].forEach(({ label, rows, tot }) => {
    subHead(label)
    colHdrs(['Category', 'Less than\n6 Months', '6 Mo to\n1 Year', '1 to 2\nYears', 'Total'])
    rows.forEach(row => row5(row.category, row.lt6, row.m6to1y, row.m1to2y, row.total))
    row5('Total', tot.lt6, tot.m6to1y, tot.m1to2y, tot.total, { isTotal: true })
    blank()
  })

  simpleNote(S.note12_cashAndCashEquivalents)
  simpleNote(S.note13_shortTermLoansAndAdvances, S.note13_shortTermLoansAndAdvances.label)
  simpleNote(S.note14_otherCurrentAssets)

  r++; addFooter(ws, r, TC)
}

// ═══════════════════════════════════════════════════════════════════════════════
// SHEET 3: PL
// ═══════════════════════════════════════════════════════════════════════════════

const buildPLSheet = (wb) => {
  const ws = wb.addWorksheet('PL', {
    views: [{ state: 'frozen', xSplit: 0, ySplit: 7 }],
    pageSetup: { paperSize: 9, orientation: 'portrait', fitToPage: true },
  })
  ws.columns = [
    { width: 6 }, { width: 38, wrapText: true }, { width: 10 }, { width: 22 }, { width: 22 },
  ]
  const TC = 5
  let r = addCompanyHeader(ws, TC, 'Profit & Loss Account for the period ended on 31st March 2024')

  // Column headers
  safeMerge(ws, r, 1, 2)
  ws.getCell(r, 1).value = 'Particulars'
  applyStyle(ws.getCell(r, 1), { bold: true, size: 11, bg: C.navyBlue, color: C.white, hAlign: 'center', border: 'medium', borderColor: C.black })
  ;['Note No', '31st March 2024', '31st March 2023'].forEach((h, i) => {
    ws.getCell(r, i + 3).value = h
    applyStyle(ws.getCell(r, i + 3), { bold: true, size: 11, bg: C.navyBlue, color: C.white, hAlign: 'center', border: 'medium', borderColor: C.black, wrapText: true })
  })
  ws.getRow(r).height = 26; r++

  const plRow = (srNo, label, note, cy, py, opts = {}) => {
    const { bold = false, isTotal = false, isSub = false } = opts
    const bg = isTotal ? C.lightGold : null
    ws.getCell(r, 1).value = srNo || ''
    applyStyle(ws.getCell(r, 1), { bold: bold || isTotal, size: 10, bg, border: 'thin' })
    ws.getCell(r, 2).value = (isSub ? '    ' : '') + (label || '')
    applyStyle(ws.getCell(r, 2), { bold: bold || isTotal, size: 10, bg, border: 'thin', wrapText: true })
    ws.getCell(r, 3).value = note || ''
    applyStyle(ws.getCell(r, 3), { hAlign: 'center', size: 10, bg, border: 'thin' })
    ;[cy, py].forEach((v, i) => {
      const cell = ws.getCell(r, i + 4)
      const n = fmt(v)
      if (n !== null) { cell.value = n; cell.numFmt = NUM_FMT }
      else { cell.value = '-' }
      applyStyle(cell, { bold: bold || isTotal, hAlign: 'right', size: 10, bg, border: 'thin' })
    })
    ws.getRow(r).height = 18; r++
  }

  const spacer = () => { ws.getRow(r).height = 6; r++ }

  const P = PL_DATA
  plRow('I.', 'Revenue from operations', P.revenue.revenueFromOperations.note, P.revenue.revenueFromOperations.cy, P.revenue.revenueFromOperations.py)
  plRow('II.', 'Other Income', P.revenue.otherIncome.note, P.revenue.otherIncome.cy, P.revenue.otherIncome.py)
  spacer()
  plRow('III.', 'Total Revenue', null, P.revenue.totalRevenue.cy, P.revenue.totalRevenue.py, { bold: true, isTotal: true })
  spacer()
  plRow('IV.', 'Expenses:', null, null, null, { bold: true })
  plRow('', 'Cost of Materials Consumed', P.expenses.costOfMaterialsConsumed.note, P.expenses.costOfMaterialsConsumed.cy, P.expenses.costOfMaterialsConsumed.py, { isSub: true })
  plRow('', 'Changes in Inventories', null, null, null, { isSub: true })
  plRow('', 'Employee benefit expenses', P.expenses.employeeBenefitExpenses.note, P.expenses.employeeBenefitExpenses.cy, P.expenses.employeeBenefitExpenses.py, { isSub: true })
  plRow('', 'Finance Costs', P.expenses.financeCosts.note, P.expenses.financeCosts.cy, P.expenses.financeCosts.py, { isSub: true })
  plRow('', 'Depreciation and Amortization Expense', P.expenses.depreciationAndAmortization.note, P.expenses.depreciationAndAmortization.cy, P.expenses.depreciationAndAmortization.py, { isSub: true })
  plRow('', 'Other expenses', P.expenses.otherExpenses.note, P.expenses.otherExpenses.cy, P.expenses.otherExpenses.py, { isSub: true })
  spacer()
  plRow('V.', 'Total Expenses', null, P.expenses.totalExpenses.cy, P.expenses.totalExpenses.py, { bold: true, isTotal: true })
  spacer()
  plRow('VI', 'Profit before tax for the year', null, P.profitBeforeTax.cy, P.profitBeforeTax.py, { bold: true, isTotal: true })
  spacer()
  plRow('VII', 'Tax expense:', null, null, null, { bold: true })
  plRow('', 'Current tax', null, P.taxExpense.currentTax.cy, P.taxExpense.currentTax.py, { isSub: true })
  plRow('', 'Deferred tax', null, P.taxExpense.deferredTax.cy, P.taxExpense.deferredTax.py, { isSub: true })
  plRow('', 'Earlier Year Tax Adjustment A/c', null, null, null, { isSub: true })
  plRow('', '', null, P.taxExpense.totalTax.cy, P.taxExpense.totalTax.py, { bold: true })
  spacer()
  plRow('VIII.', 'Profit after tax for the year', null, P.profitAfterTax.cy, P.profitAfterTax.py, { bold: true, isTotal: true })
  spacer()
  plRow('IX.', 'Earning per equity share:', null, null, null, { bold: true })
  plRow('', 'Basic', null, P.earningsPerShare.basic.cy, P.earningsPerShare.basic.py, { isSub: true })
  plRow('', 'Diluted', null, P.earningsPerShare.diluted.cy, P.earningsPerShare.diluted.py, { isSub: true })

  r++; addFooter(ws, r, TC)
}

// ═══════════════════════════════════════════════════════════════════════════════
// SHEET 4: PL SCHEDULE
// ═══════════════════════════════════════════════════════════════════════════════

const buildPLScheduleSheet = (wb) => {
  const ws = wb.addWorksheet('PL Schedule')
  ws.columns = [{ width: 46, wrapText: true }, { width: 22 }, { width: 22 }]
  const TC = 3
  let r = addCompanyHeader(ws, TC, 'Schedules forming part of Profit & Loss Account for the year ended on 31st March 2024')

  const noteHdr = (title) => {
    mergeCenter(ws, r, 1, TC, title, {
      bold: true, underline: true, size: 11, bg: C.lightBlue, color: C.navyBlue, border: 'medium',
    })
    ws.getRow(r).height = 20; r++
  }

  const colHdrs = () => {
    ;['Particulars', '31.03.2024', '31.03.2023'].forEach((h, i) => {
      ws.getCell(r, i + 1).value = h
      applyStyle(ws.getCell(r, i + 1), { bold: true, size: 11, bg: C.navyBlue, color: C.white, hAlign: 'center', border: 'medium', borderColor: C.black })
    })
    ws.getRow(r).height = 22; r++
  }

  const row3 = (label, cy, py, opts = {}) => {
    const { bold = false, isTotal = false, isSub = false, italic = false } = opts
    const bg = isTotal ? C.lightGold : null
    ws.getCell(r, 1).value = (isSub ? '    ' : '') + label
    applyStyle(ws.getCell(r, 1), { bold: bold || isTotal, italic, size: 10, bg, border: 'thin', wrapText: true })
    ;[cy, py].forEach((v, i) => {
      const cell = ws.getCell(r, i + 2)
      const n = fmt(v)
      if (n !== null) { cell.value = n; cell.numFmt = NUM_FMT }
      else { cell.value = '-' }
      applyStyle(cell, { bold: bold || isTotal, hAlign: 'right', size: 10, bg, border: 'thin' })
    })
    ws.getRow(r).height = 17; r++
  }

  const blank = () => { ws.getRow(r).height = 8; r++ }

  const simpleNotePS = (note) => {
    noteHdr(note.title); colHdrs()
    note.items.forEach(item => row3(item.name, item.cy, item.py, { isSub: true }))
    row3('TOTAL', note.total.cy, note.total.py, { isTotal: true })
    blank()
  }

  const PS = PL_SCHEDULE_DATA
  simpleNotePS(PS.note15_revenueFromOperations)
  simpleNotePS(PS.note16_otherIncome)
  simpleNotePS(PS.note17_costOfMaterials)
  simpleNotePS(PS.note18_employeeBenefits)

  noteHdr(PS.note19_financeCost.title); colHdrs()
  row3(PS.note19_financeCost.label, null, null, { italic: true })
  PS.note19_financeCost.items.forEach(item => row3(item.name, item.cy, item.py, { isSub: true }))
  row3('TOTAL...', PS.note19_financeCost.total.cy, PS.note19_financeCost.total.py, { isTotal: true })
  blank()

  noteHdr(PS.note20_otherExpenses.title); colHdrs()
  PS.note20_otherExpenses.items.forEach(item => row3(item.name, item.cy, item.py, { isSub: true }))
  row3('TOTAL...', PS.note20_otherExpenses.total.cy, PS.note20_otherExpenses.total.py, { isTotal: true })

  r++; addFooter(ws, r, TC)
}

// ═══════════════════════════════════════════════════════════════════════════════
// SHEET 5: FA NOTE 9
// ═══════════════════════════════════════════════════════════════════════════════

const buildFANoteSheet = (wb) => {
  const ws = wb.addWorksheet('FA Note 9')
  ws.columns = [
    { width: 24 },
    { width: 13 }, { width: 13 }, { width: 14 }, { width: 13 },
    { width: 13 }, { width: 13 }, { width: 14 }, { width: 13 },
    { width: 13 }, { width: 13 },
  ]
  const TC = 11
  let r = addCompanyHeader(ws, TC, 'Note 9: Depreciation as per Companies Act, 2013')

  mergeCenter(ws, r, 1, TC, '(Amount in Rs.)', { hAlign: 'right', italic: true, size: 9 })
  ws.getRow(r).height = 14; r++

  // Main group headers
  ws.getCell(r, 1).value = 'Name of the Asset'
  applyStyle(ws.getCell(r, 1), { bold: true, size: 10, bg: C.gold, border: 'medium', borderColor: C.black, hAlign: 'center', vAlign: 'middle' })
  safeMerge(ws, r, 2, 5); ws.getCell(r, 2).value = 'GROSS BLOCK'
  applyStyle(ws.getCell(r, 2), { bold: true, size: 11, bg: C.navyBlue, color: C.white, hAlign: 'center', border: 'medium', borderColor: C.black })
  safeMerge(ws, r, 6, 9); ws.getCell(r, 6).value = 'DEPRECIATION'
  applyStyle(ws.getCell(r, 6), { bold: true, size: 11, bg: C.navyBlue, color: C.white, hAlign: 'center', border: 'medium', borderColor: C.black })
  safeMerge(ws, r, 10, 11); ws.getCell(r, 10).value = 'NET BLOCK'
  applyStyle(ws.getCell(r, 10), { bold: true, size: 11, bg: C.navyBlue, color: C.white, hAlign: 'center', border: 'medium', borderColor: C.black })
  ws.getRow(r).height = 22; r++

  // Sub-headers
  ;['', '01.04.23', 'Additions', 'Deletions/\nAdjustment', '31.03.2024',
    '01.04.23', 'Dep for\nthe year', 'Deletions/\nAdjustment', '31.03.2024',
    '31.03.2024', '31.03.23'].forEach((h, i) => {
      ws.getCell(r, i + 1).value = h
      applyStyle(ws.getCell(r, i + 1), { bold: true, size: 9, bg: C.lightBlue, color: C.navyBlue, hAlign: 'center', border: 'thin', wrapText: true })
    })
  ws.getRow(r).height = 32; r++

  const faRow = (name, gb, dep, nb, isTotal = false) => {
    const bg = isTotal ? C.gold : null
    ws.getCell(r, 1).value = name
    applyStyle(ws.getCell(r, 1), { bold: isTotal, size: 10, bg, border: 'thin' })
    ;[gb.opening, gb.additions, gb.deletions, gb.closing,
      dep.opening, dep.forYear, dep.deletions, dep.closing,
      nb.cy, nb.py].forEach((v, i) => {
        const cell = ws.getCell(r, i + 2)
        const n = fmt(v)
        if (n !== null && n !== 0) { cell.value = n; cell.numFmt = NUM_FMT }
        else { cell.value = '-' }
        applyStyle(cell, { bold: isTotal, size: 10, hAlign: 'right', bg, border: 'thin' })
      })
    ws.getRow(r).height = 18; r++
  }

  FA_NOTE_DATA.assets.forEach(asset => faRow(asset.name, asset.grossBlock, asset.depreciation, asset.netBlock))
  ws.getRow(r).height = 6; r++
  const tot = FA_NOTE_DATA.totals
  faRow('TOTAL', tot.grossBlock, tot.depreciation, tot.netBlock, true)

  r += 2; addFooter(ws, r, TC)
}

// ═══════════════════════════════════════════════════════════════════════════════
// MAIN EXPORT
// ═══════════════════════════════════════════════════════════════════════════════

export const generateBSReportExcel = async () => {
  try {
    console.log('=== BS Report Excel Generation Started ===')

    const workbook = new ExcelJS.Workbook()
    workbook.creator = 'iSmart Accounts System'
    workbook.created = new Date()
    workbook.modified = new Date()

    buildBSSheet(workbook)
    buildBSScheduleSheet(workbook)
    buildPLSheet(workbook)
    buildPLScheduleSheet(workbook)
    buildFANoteSheet(workbook)

    const buffer = await workbook.xlsx.writeBuffer()
    const timestamp = new Date().toISOString().slice(0, 10)
    const filename = `Balance_Sheet_${timestamp}.xlsx`
    const blob = new Blob([buffer], {
      type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    })
    saveAs(blob, filename)

    console.log('✓ BS Report Excel generated successfully:', filename)
    return { success: true, filename }
  } catch (err) {
    console.error('generateBSReportExcel error:', err)
    throw new Error(`Failed to generate Balance Sheet Excel: ${err.message}`)
  }
}

export default { generateBSReportExcel }
